name: Generate Snake

on:
  # roda automaticamente todo dia à meia-noite (UTC)
  schedule:
    - cron: "0 0 * * *"
  # permite rodar manualmente pelo botão "Run workflow"
  workflow_dispatch:
  # roda sempre que você der push na branch main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar a cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg?palette=github-light

      - name: Publicar na branch "output"
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
